[package]
name = "cli_game"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.81", features = ["backtrace"] }
crossterm = "0.27.0"
enum_dispatch = "0.3.12"
hecs = "0.10.4"
ratatui = "0.26.1"
rayon = "1.9.0"
